[package]
name = "advent-of-code"
version = "1.0.0"
edition = "2021"

[dependencies]
aoc-client = "0.2.0"
clap = { version = "4.5.23", features = ["derive"] }
either = "1.13.0"
regex = "1.11.1"
unindent = "0.2.3"
